### ISSUE TITLE
Turning off plasma and kerr in prop_capillary

### ISSUE THREAD

**Issue by MaikeLenz** [LupoLab/Luna.jl#270]
Dear Chris,

I hope you're well!
I tried propagating a pulse with both ionisation and the kerr effect turned off by adding the arguments "plasma = false" and "kerr = false" in prop_capillary. When I use these individually, everything works. However, whenever I try to turn both off I get an error saying "'InexactError: trunc(Int64, NaN)' occurred while calling julia code" - should I be turning both of these off simultaneously with a different method?

Thanks for your help!
Maike

**Comment by chrisbrahms** [comment]
Sorry about this, I told you to use something that I should've known would break. I can't reproduce your exact error, but the reason for this is probably because the solver can't currently deal with propagations in which there is no nonlinearity at all. Basically the step-size controller divides by zero. #271 will fix this.

Until then you can try switching plasma off manually and additionally reducing the pulse energy to something really tiny (e.g. to a few picojoules). This should have mostly the same effect as switching of the Kerr effect entirely.
