### ISSUE TITLE
Recreate figure from Chemical Science

### ISSUE THREAD

**Issue by slj2001** [LupoLab/Luna.jl#289]
Recently published article in Chemical Science Kotisina et al. DOI: 10.1039/d2sc02185d has a figure (Fig. 2) with input parameters given as:
10 fs FWHM
800 nm 
50 cm HCF
150 um core diameter
500 mbar Ar (decreasing gradient) 

RDW is seen at 280 nm in the numerical simulation at the 50 cm cut-through. 

An attempt at recreating this with the command (ignoring the gradient pressure)
output = prop_capillary(150e-6, .5, :Ar, .5; λ0=800e-9, energy=50e-6, τfwhm=10e-15, λlims=(150e-9, 4e-6), trange=1e-12)

and similarly with gradient pressure
output = prop_capillary(150e-6, .5, :Ar, (.5, 0); λ0=800e-9, energy=50e-6, τfwhm=10e-15, λlims=(150e-9, 4e-6), trange=1e-12)

both result in the same unsatisfactory simulation. Please advise! Many thanks. 

<img width="899" alt="image" src="https://user-images.githubusercontent.com/112559606/187683344-14482575-2de1-4ed6-83f1-e1892a6871f9.png">

**Comment by chrisbrahms** [comment]
The first argument to `prop_capillary` is the core **radius**, not the core **diameter**. See http://lupo-lab.com/Luna.jl/stable/interface.html

To add a pressure gradient, replace the pressure argument `0.5` with `(0.5, 0)`, i.e. a 2-`Tuple` of numbers which give the pressure at the input and output of the HCF.

Because ionisation plays an important role for these parameters, you also definitely want to use multi-mode propagation by setting the `modes` keyword argument to some number (usually around 4-8 is enough).

With the commands
```julia
julia> output = prop_capillary(75e-6, .5, :Ar, (.5, 0);
    λ0=800e-9, energy=50e-6, τfwhm=10e-15,
    λlims=(150e-9, 4e-6), trange=1e-12, modes=4)
[...]
julia> Plotting.spec_1D(output, [0, 0.25, 0.5]; modes=:sum)
```
I get this:
<img width="729" alt="image" src="https://user-images.githubusercontent.com/38351086/187701694-326f71cb-fb20-41eb-ae96-989c8ec70483.png">

**Comment by chrisbrahms** [comment]
@slj2001 I will close this issue. if your problem is not yet fixed, please re-open it.
