### ISSUE TITLE
Phase term of plasma effect in the propagation of ultrafast light pulses

### ISSUE THREAD

**Issue by islent** [LupoLab/Luna.jl#301]
Hello,

I'm investigating plasma effect in the propagation of ultrafast light pulses. I read several papers and found that the plasma term varies among different models. My questions are about the so-called phase term in `Geissler et al. 1999`:
1. it does not have an `im` coefficient;
2. it is in the integrated form.

- Geissler et al. 1999
![Geissler 1999](https://user-images.githubusercontent.com/31057826/197968376-26fb9d83-afe0-4444-a551-37f52f6201f8.png)
- Brahms and Travers 2021
![Brahms and Travers 2021](https://user-images.githubusercontent.com/31057826/197968408-89fb8454-422b-46d3-bf40-250a74dd66a4.png)
- Saleh et al. 2011
![Saleh 2011](https://user-images.githubusercontent.com/31057826/197968433-b02b7445-a4ac-4807-8b92-f0eb3611118c.png)
- Fedotov et al. 2007
![Fedotov 2007](https://user-images.githubusercontent.com/31057826/197968526-54cc02dd-5492-417f-92c7-415be8169fdd.png)
- Sprangle et al. 2002
![Sprangle 2002-1](https://user-images.githubusercontent.com/31057826/197968500-438cd4bc-fddd-4c62-a218-921503730062.png)
![Sprangle 2002-2](https://user-images.githubusercontent.com/31057826/197968550-a490087e-87c5-4e2b-b046-e75a3f3615be.png)
![Sprangle 2002-3](https://user-images.githubusercontent.com/31057826/197968562-d91f11cf-1bf7-4882-a606-cfb63a035f84.png)
![Sprangle 2002-4](https://user-images.githubusercontent.com/31057826/197968566-008865e3-877f-445a-9e11-8e41172c9da4.png)

Could you explain:
1. Why is the "phase term" not imaginary?
2. Are there assumptions in deriving other equations, so that the integration can be simplified?
3. Why does `Luna.jl` implement the FOP method in `Geissler et al. 1999` instead of the others?

Many thanks.

### References
- Geissler, M.; Tempea, G.; Scrinzi, A.; Schnürer, M.; Krausz, F.; Brabec, T. Light Propagation in Field-Ionizing Media: Extreme Nonlinear Optics. Physical review letters 1999, 83 (15), 2930.
- Brahms, C.; Travers, J. C. Timing and Energy Stability of Resonant Dispersive Wave Emission in Gas-Filled Hollow-Core Waveguides. Journal of Physics: Photonics 2021, 3 (2), 025004.
- Saleh, M. F.; Chang, W.; Hölzer, P.; Nazarkin, A.; Travers, J. C.; Joly, N. Y.; Russell, P. St. J.; Biancalana, F. Theory of Photoionization-Induced Blueshift of Ultrashort Solitons in Gas-Filled Hollow-Core Photonic Crystal Fibers. Phys. Rev. Lett. 2011, 107 (20), 203902. https://doi.org/10.1103/PhysRevLett.107.203902.
- Fedotov, A. B.; Serebryannikov, E. E.; Zheltikov, A. M. Ionization-Induced Blueshift of High-Peak-Power Guided-Wave Ultrashort Laser Pulses in Hollow-Core Photonic-Crystal Fibers. Phys. Rev. A 2007, 76 (5), 053811. https://doi.org/10.1103/PhysRevA.76.053811.
- Sprangle, P.; Peñano, J. R.; Hafizi, B. Propagation of Intense Short Laser Pulses in the Atmosphere. Phys. Rev. E 2002, 66 (4), 046418. https://doi.org/10.1103/PhysRevE.66.046418.

**Comment by chrisbrahms** [comment]
Hi!

There is lots of detail in this topic which is too much to write down in a quick answer, but I'll try to help you out on the three questions. The key thing to remember is the distinction between envelope equations and field equations, i.e. those for real-valued or complex-valued (analytic) fields.

> Why is the "phase term" not imaginary?
Note that the polarisation term is a) written in the time domain and b) written for *real-valued* electric fields. This means that there *shouldn't* be any imaginary terms anywhere. The phase term modulates the phase of the electric field by multiplying with the (quickly varying) electron density. Note also that if you take the electron density to be constant, the double integral over time is only over the field, and the prefactor including the (constant) electron density turns into the plasma frequency. In the frequency domain the integral turns into multiplication by -ω^2 so you get back the simple expression for the susceptibility of the plasma at constant density.

> Are there assumptions in deriving other equations, so that the integration can be simplified?
I take it your question is why we have to do the double integral but others don't? The main reason the combination of the first answer above and the slowly varying envelope approximation, which means that you can write the equation with an explicit (imaginary) phase modulating term in the time domain and ignore the fast changes in the electron density.

> Why does Luna.jl implement the FOP method in Geissler et al. 1999 instead of the others?
The short answer is that it's the most accurate (remember that very importantly, all of these models are wrong, just to different degrees). It's one of the few models which work for real-valued fields and capture the fast sub-cycle changes in the electron density. Though note that Luna.jl does *not* use the actual propagation equation derived in Geissler 1999. We just use their model for the nonlinear polarisation due to the plasma and insert it into the UPPE.

Hope this helps!

**Comment by islent** [comment]
Sorry for late reply.

> Note that the polarisation term is a) written in the time domain and b) written for real-valued electric fields. This means that there shouldn't be any imaginary terms anywhere.

This helped me to take a great step forward, but I haven't been able to take much time to fully derive the equations above. I would continue on this topic after I have a better understanding of physical processes in the propagation of plasma induced laser pulses.

Many thanks for your kind and warm help!
