### ISSUE TITLE
Scan seems to give same results with different sets of input parameters

### ISSUE THREAD

**Issue by hamid91hh** [LupoLab/Luna.jl#305]
I just noticed the results are the same when I run a scan with two different sets of input parameters.
In the simplest case, I just run scan.jl. and I used gas = :HeJ  and gas = :Ar  which the outputs were the same.

**Comment by chrisbrahms** [comment]
This is probably because you've saved the scan output to disk. When you re-run the scan, Luna sees those files and assumes you've already run the simulations, so it just uses the content of the files rather than re-running the simulation (if the scan runs much faster the second time, this is why). To see the difference, delete the output files in between runs.

**Comment by chrisbrahms** [comment]
Hi @hamid91hh , did my suggestion fix your problem? If so please close this issue.
