### ISSUE TITLE
Why VSCode is much slower than using Julia terminal

### ISSUE THREAD

**Issue by layallan** [LupoLab/Luna.jl#376]
Hi I am using VSCode to debug the code but I notice that the terminal is much faster than using VSCode when running it. Does anyone know the answer? 

Thanks!

**Comment by chrisbrahms** [comment]
Hi,
I don't think issue is specific to Luna, so I can't give you a complete answer. But one question is whether you're trying use the Debug mode in VS Code. This is very different thing from running Julia code directly--rather than being compiled it is interpreted, which is many times slower. For more info see https://www.julia-vscode.org/docs/stable/userguide/debugging/

If you run your code in VS Code with the "Execute active file in REPL" command (accessible via the command palette with Cmd-Shift-P/Ctrl-Shift-P or with the little play icon in the top right corner), do you see the same difference in speed?

**Comment by layallan** [comment]
![q1](https://github.com/user-attachments/assets/8908b6e8-4541-4f1d-b474-217d7e7ff243)
I was trying to run the file in the VSCode and it always stay here, even for several hours. But when I use the terminal, it will give me the output within 5 mins. Not sure the reason.

Thanks!

**Comment by chrisbrahms** [comment]
Yes, this is exactly what I meant. You're debugging the script, not running it. Therefore, Julia runs an interpreter on the code rather than compiling it. This is orders of magnitude slower and for a package as large as Luna, basically impossible. You need to run it as I described in my first answer, then it should be exactly the same as in a terminal directly.

**Comment by layallan** [comment]
That works! Thanks Chris!
